name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kode
        uses: actions/checkout@v4

      - name: Opsæt Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Opsæt Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'

      - name: Undersøg Gradle
        run: |
           gradle projects
           gradle :app:tasks --all
           
      - name: Undersøg filer
        run: |
          pwd
          find . -maxdepth 3 -type f | sort
          echo "----- APP BUILD FILE -----"
          cat app/build.gradle.kts
          echo "----- SETTINGS -----"
          cat settings.gradle.kts
          echo "----- ROOT BUILD -----"
          cat build.gradle.kts

      - name: Undersøg Gradle
        run: |
          gradle projects
          gradle :app:tasks --all
          
      - name: Gem APK
        uses: actions/upload-artifact@v4
        with:
          name: Hitster-TIDAL-debug
          path: app/build/outputs/apk/debug/app-debug.apk
